using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.Android;
using UnityEditor.Build;
using UnityEngine;

namespace Ronriku.Editor
{
    /// <summary>
    /// Assigns the app icons generated by <c>store/tools/make_art.py</c> (Assets/Ronriku/Art/Icon):
    /// the default icon and the Android adaptive icon (background + foreground layer, 6 densities).
    /// Idempotent; also called by the Android builds so a release never ships the Unity default icon.
    /// Batch mode: <c>-executeMethod Ronriku.Editor.RonrikuIcon.Apply</c>.
    /// </summary>
    public static class RonrikuIcon
    {
        public const string IconFolder = "Assets/Ronriku/Art/Icon";
        private const string Master = IconFolder + "/ronriku-icon-512.png";

        [MenuItem("RONRIKU/Apply Icons")]
        public static void Apply() => TryApply(logSuccess: true);

        /// <summary>Returns false (with a warning) when the icon files are missing.</summary>
        public static bool TryApply(bool logSuccess)
        {
            if (!File.Exists(Master))
            {
                Debug.LogWarning($"RONRIKU icons: {Master} not found. Run `python store/tools/make_art.py` in the repo root.");
                return false;
            }

            AssetDatabase.ImportAsset(IconFolder, ImportAssetOptions.ImportRecursive);
            foreach (string guid in AssetDatabase.FindAssets("t:Texture2D", new[] { IconFolder }))
                ConfigureImporter(AssetDatabase.GUIDToAssetPath(guid));

            Texture2D master = Load(Master);
            if (master == null)
            {
                Debug.LogWarning("RONRIKU icons: master icon did not import.");
                return false;
            }

            // Default icon (used by every platform without its own set).
            PlayerSettings.SetIcons(NamedBuildTarget.Unknown, new[] { master }, IconKind.Any);

            int assigned = 0;
            assigned += AssignAndroid(AndroidPlatformIconKind.Adaptive, size => new[]
            {
                Load($"{IconFolder}/ronriku-adaptive-bg-{size}.png"), // layer 0 = background
                Load($"{IconFolder}/ronriku-adaptive-fg-{size}.png"), // layer 1 = foreground
            });
            // Unity 6.6 only has Adaptive for Android (Legacy/Round are obsolete; minSdk 26 = every device
            // supports adaptive icons). The legacy/round PNGs stay in the folder for other stores and the web.

            AssetDatabase.SaveAssets();
            if (logSuccess) Debug.Log($"RONRIKU_ICONS_APPLIED android_slots={assigned}");
            return true;
        }

        private static int AssignAndroid(PlatformIconKind kind, System.Func<int, Texture2D[]> texturesForSize)
        {
            PlatformIcon[] icons = PlayerSettings.GetPlatformIcons(NamedBuildTarget.Android, kind);
            int count = 0;
            foreach (PlatformIcon icon in icons)
            {
                Texture2D[] textures = texturesForSize(icon.width);
                if (textures == null || System.Array.Exists(textures, t => t == null))
                {
                    Debug.LogWarning($"RONRIKU icons: missing {kind} {icon.width}px texture; slot left as is.");
                    continue;
                }
                icon.SetTextures(textures);
                count++;
            }
            PlayerSettings.SetPlatformIcons(NamedBuildTarget.Android, kind, icons);
            return count;
        }

        private static Texture2D Load(string path) => AssetDatabase.LoadAssetAtPath<Texture2D>(path);

        /// <summary>Pixel art: point filtering, no mipmaps, lossless.</summary>
        private static void ConfigureImporter(string path)
        {
            if (AssetImporter.GetAtPath(path) is not TextureImporter importer) return;
            bool dirty = importer.textureType != TextureImporterType.Default
                         || importer.filterMode != FilterMode.Point
                         || importer.mipmapEnabled
                         || importer.npotScale != TextureImporterNPOTScale.None
                         || importer.textureCompression != TextureImporterCompression.Uncompressed
                         || !importer.alphaIsTransparency;
            if (!dirty) return;
            importer.textureType = TextureImporterType.Default;
            importer.filterMode = FilterMode.Point;
            importer.mipmapEnabled = false;
            importer.npotScale = TextureImporterNPOTScale.None;
            importer.textureCompression = TextureImporterCompression.Uncompressed;
            importer.alphaIsTransparency = true;
            importer.SaveAndReimport();
        }

        /// <summary>Sizes the generator produces, for reference and tests.</summary>
        public static readonly IReadOnlyList<int> LegacySizes = new[] { 192, 144, 96, 72, 48, 36 };
        public static readonly IReadOnlyList<int> AdaptiveSizes = new[] { 432, 324, 216, 162, 108, 81 };
    }
}
